version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
proxy:
  remoteurl: https://registry-1.docker.io
  remotehostquerykey: ns
  remotehostconfigmap:
    docker.io:
      remoteurl: https://registry-1.docker.io
    registry.k8s.io:
      remoteurl: https://registry.k8s.io
    gcr.io:
      remoteurl: https://gcr.io
    quay.io:
      remoteurl: https://quay.io
    ghcr.io:
      remoteurl: https://ghcr.io
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
