version: '2'

networks:
  test:

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - test

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    #container_name: kafka  # remove if you want to run multiple brokers
    environment:
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092   # remove if you want to run multiple brokers
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # remove if you want to run multiple brokers
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1  # your docker host IP (Note: Do not use localhost or 127.0.0.1 as the host ip if you want to run multiple brokers.)
      #KAFKA_ADVERTISED_PORT: 9092  # remove if you want to run multiple brokers
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "javainuse-topic:1:1"   # Topic명:Partition개수:Replica개수
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092"
    depends_on:
      - zookeeper
    networks:
      - test